//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDstudents.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        private int TotalMarksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TotalMarks {
            get {
                return this.TotalMarksField;
            }
            set {
                if ((this.TotalMarksField.Equals(value) != true)) {
                    this.TotalMarksField = value;
                    this.RaisePropertyChanged("TotalMarks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.StudentsWebServiceSoap")]
    public interface StudentsWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        CRUDstudents.ServiceReference1.HelloWorldResponse HelloWorld(CRUDstudents.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<CRUDstudents.ServiceReference1.HelloWorldResponse> HelloWorldAsync(CRUDstudents.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetStudentsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudents", ReplyAction="*")]
        CRUDstudents.ServiceReference1.GetStudentsResponse GetStudents(CRUDstudents.ServiceReference1.GetStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudents", ReplyAction="*")]
        System.Threading.Tasks.Task<CRUDstudents.ServiceReference1.GetStudentsResponse> GetStudentsAsync(CRUDstudents.ServiceReference1.GetStudentsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public CRUDstudents.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(CRUDstudents.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRUDstudents.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(CRUDstudents.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudents", Namespace="http://tempuri.org/", Order=0)]
        public CRUDstudents.ServiceReference1.GetStudentsRequestBody Body;
        
        public GetStudentsRequest() {
        }
        
        public GetStudentsRequest(CRUDstudents.ServiceReference1.GetStudentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStudentsRequestBody {
        
        public GetStudentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRUDstudents.ServiceReference1.GetStudentsResponseBody Body;
        
        public GetStudentsResponse() {
        }
        
        public GetStudentsResponse(CRUDstudents.ServiceReference1.GetStudentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRUDstudents.ServiceReference1.Student[] GetStudentsResult;
        
        public GetStudentsResponseBody() {
        }
        
        public GetStudentsResponseBody(CRUDstudents.ServiceReference1.Student[] GetStudentsResult) {
            this.GetStudentsResult = GetStudentsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudentsWebServiceSoapChannel : CRUDstudents.ServiceReference1.StudentsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentsWebServiceSoapClient : System.ServiceModel.ClientBase<CRUDstudents.ServiceReference1.StudentsWebServiceSoap>, CRUDstudents.ServiceReference1.StudentsWebServiceSoap {
        
        public StudentsWebServiceSoapClient() {
        }
        
        public StudentsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRUDstudents.ServiceReference1.HelloWorldResponse CRUDstudents.ServiceReference1.StudentsWebServiceSoap.HelloWorld(CRUDstudents.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            CRUDstudents.ServiceReference1.HelloWorldRequest inValue = new CRUDstudents.ServiceReference1.HelloWorldRequest();
            inValue.Body = new CRUDstudents.ServiceReference1.HelloWorldRequestBody();
            CRUDstudents.ServiceReference1.HelloWorldResponse retVal = ((CRUDstudents.ServiceReference1.StudentsWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRUDstudents.ServiceReference1.HelloWorldResponse> CRUDstudents.ServiceReference1.StudentsWebServiceSoap.HelloWorldAsync(CRUDstudents.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRUDstudents.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            CRUDstudents.ServiceReference1.HelloWorldRequest inValue = new CRUDstudents.ServiceReference1.HelloWorldRequest();
            inValue.Body = new CRUDstudents.ServiceReference1.HelloWorldRequestBody();
            return ((CRUDstudents.ServiceReference1.StudentsWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRUDstudents.ServiceReference1.GetStudentsResponse CRUDstudents.ServiceReference1.StudentsWebServiceSoap.GetStudents(CRUDstudents.ServiceReference1.GetStudentsRequest request) {
            return base.Channel.GetStudents(request);
        }
        
        public CRUDstudents.ServiceReference1.Student[] GetStudents() {
            CRUDstudents.ServiceReference1.GetStudentsRequest inValue = new CRUDstudents.ServiceReference1.GetStudentsRequest();
            inValue.Body = new CRUDstudents.ServiceReference1.GetStudentsRequestBody();
            CRUDstudents.ServiceReference1.GetStudentsResponse retVal = ((CRUDstudents.ServiceReference1.StudentsWebServiceSoap)(this)).GetStudents(inValue);
            return retVal.Body.GetStudentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRUDstudents.ServiceReference1.GetStudentsResponse> CRUDstudents.ServiceReference1.StudentsWebServiceSoap.GetStudentsAsync(CRUDstudents.ServiceReference1.GetStudentsRequest request) {
            return base.Channel.GetStudentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRUDstudents.ServiceReference1.GetStudentsResponse> GetStudentsAsync() {
            CRUDstudents.ServiceReference1.GetStudentsRequest inValue = new CRUDstudents.ServiceReference1.GetStudentsRequest();
            inValue.Body = new CRUDstudents.ServiceReference1.GetStudentsRequestBody();
            return ((CRUDstudents.ServiceReference1.StudentsWebServiceSoap)(this)).GetStudentsAsync(inValue);
        }
    }
}
